//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.PlayerManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.PlayerManagement.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong setting for languages..
        /// </summary>
        internal static string AntColonyLanguageNotValid {
            get {
                return ResourceManager.GetString("AntColonyLanguageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can only contain letters and numbers, is not allowed to begin with a number and needs to be between 2 and 20 characters long..
        /// </summary>
        internal static string AntColonyNameNotValid {
            get {
                return ResourceManager.GetString("AntColonyNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder does not exist..
        /// </summary>
        internal static string AntColonyOutputFolderDoesNotExist {
            get {
                return ResourceManager.GetString("AntColonyOutputFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string AntPropertiesAuthorFormat {
            get {
                return ResourceManager.GetString("AntPropertiesAuthorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to a database.
        /// </summary>
        internal static string AntPropertiesDbAccess {
            get {
                return ResourceManager.GetString("AntPropertiesDbAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the file system.
        /// </summary>
        internal static string AntPropertiesIoAccess {
            get {
                return ResourceManager.GetString("AntPropertiesIoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the network.
        /// </summary>
        internal static string AntPropertiesNetAccess {
            get {
                return ResourceManager.GetString("AntPropertiesNetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access limitation.
        /// </summary>
        internal static string AntPropertiesNoAccess {
            get {
                return ResourceManager.GetString("AntPropertiesNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No further information available..
        /// </summary>
        internal static string AntPropertiesNoAdditionalInfos {
            get {
                return ResourceManager.GetString("AntPropertiesNoAdditionalInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant references external assembly or assemblies..
        /// </summary>
        internal static string AntPropertiesRefAccess {
            get {
                return ResourceManager.GetString("AntPropertiesRefAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of {0}.
        /// </summary>
        internal static string AntPropertiesTitle {
            get {
                return ResourceManager.GetString("AntPropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the user interface.
        /// </summary>
        internal static string AntPropertiesUiAccess {
            get {
                return ResourceManager.GetString("AntPropertiesUiAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string AntPropertiesUnknown {
            get {
                return ResourceManager.GetString("AntPropertiesUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following rights are not granted in the settings:.
        /// </summary>
        internal static string SimulationPluginRightsLocked {
            get {
                return ResourceManager.GetString("SimulationPluginRightsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This colony creates a ruleViolation with current settings: {0}.
        /// </summary>
        internal static string SimulationPluginRuleViolation {
            get {
                return ResourceManager.GetString("SimulationPluginRuleViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
