//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Plugin.Simulation.Generators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneratorFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneratorFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Plugin.Simulation.Generators.GeneratorFiles", typeof(GeneratorFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using AntMe.Deutsch;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace AntMe.Player
        ///{
        ///    [Spieler(
        ///        Volkname = &quot;Template&quot;,
        ///        Vorname = &quot;Tom&quot;,
        ///        Nachname = &quot;Wendel&quot;
        ///    )]
        ///    [Kaste(
        ///        Name = &quot;Standard&quot;,
        ///        AngriffModifikator = 0,
        ///        DrehgeschwindigkeitModifikator = 0,
        ///        EnergieModifikator = 0,
        ///        GeschwindigkeitModifikator = 0,
        ///        LastModifikator = 0,
        ///        ReichweiteModifikator = 0,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_de {
            get {
                return ResourceManager.GetString("class_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using AntMe.English;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace AntMe.Player.Template
        ///{
        ///    [Player(
        ///        ColonyName = &quot;English Ants&quot;,
        ///        FirstName = &quot;Tom&quot;,
        ///        LastName = &quot;Wendel&quot;
        ///    )]
        ///    [Caste(
        ///        Name = &quot;Default&quot;,
        ///        AttackModificator = 0,
        ///        EnergyModificator = 0,
        ///        LoadModificator = 0,
        ///        RangeModificator = 0,
        ///        RotationSpeedModificator = 0,
        ///        SpeedModificator = 0,
        ///        Vi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string class_en {
            get {
                return ResourceManager.GetString("class_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup Condition=&quot;&apos;$(Configuration)|$(Platform)&apos; == &apos;Debug|AnyCPU&apos;&quot;&gt;
        ///    &lt;StartAction&gt;Program&lt;/StartAction&gt;
        ///    &lt;StartProgram&gt;C:\Program Files %28x86%29\AntMe 1.7\AntMe.exe&lt;/StartProgram&gt;
        ///    &lt;StartArguments&gt;/file=&quot;C:\Users\Tom\Documents\Visual Studio 2013\Projects\AntMe! 1.7 Template\bin\Debug\AntMe.Player.Template.dll&quot;&lt;/StartArguments&gt;
        ///  &lt;/PropertyGroup&gt;
        ///&lt;/Proje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 2013
        ///VisualStudioVersion = 12.0.31101.0
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;AntMe! 1.7 Template&quot;, &quot;AntMe! 1.7 Template.csproj&quot;, &quot;{CF0D4569-6684-4406-8E9D-D18C24106DDF}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release|Any CPU = Release|Any CPU
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string solution {
            get {
                return ResourceManager.GetString("solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup Condition=&quot;&apos;$(Configuration)|$(Platform)&apos; == &apos;Debug|AnyCPU&apos;&quot;&gt;
        ///    &lt;StartAction&gt;Program&lt;/StartAction&gt;
        ///    &lt;StartProgram&gt;C:\Program Files %28x86%29\AntMe 1.7\AntMe.exe&lt;/StartProgram&gt;
        ///    &lt;StartArguments&gt;/file=&quot;C:\Users\Tom\Documents\Visual Studio 2013\Projects\AntMe! 1.7 Template\bin\Debug\AntMe.Player.Template.dll&quot;&lt;/StartArguments&gt;
        ///  &lt;/PropertyGroup&gt;
        ///&lt;/Proje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
