//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Plugin.Simulation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Plugin.Simulation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string AntPropertiesAuthorFormat {
            get {
                return ResourceManager.GetString("AntPropertiesAuthorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to a database.
        /// </summary>
        internal static string AntPropertiesDbAccess {
            get {
                return ResourceManager.GetString("AntPropertiesDbAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the file system.
        /// </summary>
        internal static string AntPropertiesIoAccess {
            get {
                return ResourceManager.GetString("AntPropertiesIoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the network.
        /// </summary>
        internal static string AntPropertiesNetAccess {
            get {
                return ResourceManager.GetString("AntPropertiesNetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access limitation.
        /// </summary>
        internal static string AntPropertiesNoAccess {
            get {
                return ResourceManager.GetString("AntPropertiesNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant references external assembly or assemblies..
        /// </summary>
        internal static string AntPropertiesRefAccess {
            get {
                return ResourceManager.GetString("AntPropertiesRefAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the user interface.
        /// </summary>
        internal static string AntPropertiesUiAccess {
            get {
                return ResourceManager.GetString("AntPropertiesUiAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Free Game Mode allows to arrange free games.
        /// </summary>
        internal static string FreeGamePluginDescription {
            get {
                return ResourceManager.GetString("FreeGamePluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Game.
        /// </summary>
        internal static string FreeGamePluginName {
            get {
                return ResourceManager.GetString("FreeGamePluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem during runtime: {0}.
        /// </summary>
        internal static string SimulationPluginExcetionIntro {
            get {
                return ResourceManager.GetString("SimulationPluginExcetionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {3}.
        /// </summary>
        internal static string SimulationPluginKicklistEntry {
            get {
                return ResourceManager.GetString("SimulationPluginKicklistEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following colonies are not valid anymore: .
        /// </summary>
        internal static string SimulationPluginKicklistHead {
            get {
                return ResourceManager.GetString("SimulationPluginKicklistHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntMe! - Simulation.
        /// </summary>
        internal static string SimulationPluginMessageBoxTitle {
            get {
                return ResourceManager.GetString("SimulationPluginMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This colony creates a ruleViolation with current settings: {0}.
        /// </summary>
        internal static string SimulationPluginRuleViolation {
            get {
                return ResourceManager.GetString("SimulationPluginRuleViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant simulation.
        /// </summary>
        internal static string SimulatorPluginDescription {
            get {
                return ResourceManager.GetString("SimulatorPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Game.
        /// </summary>
        internal static string SimulatorPluginName {
            get {
                return ResourceManager.GetString("SimulatorPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation has not been started..
        /// </summary>
        internal static string SimulatorPluginNotStarted {
            get {
                return ResourceManager.GetString("SimulatorPluginNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} coun&apos;t be loaded. The detailed errormessage is &apos;{1}&apos;.
        /// </summary>
        internal static string SimulatorPluginTeamSetupFileloadException {
            get {
                return ResourceManager.GetString("SimulatorPluginTeamSetupFileloadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the file {0} was no AI found..
        /// </summary>
        internal static string SimulatorPluginTeamSetupNoFolksFound {
            get {
                return ResourceManager.GetString("SimulatorPluginTeamSetupNoFolksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} contains AI, but they are already contained in the list..
        /// </summary>
        internal static string SimulatorPluginTeamSetupStillLoaded {
            get {
                return ResourceManager.GetString("SimulatorPluginTeamSetupStillLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows simulation statistics..
        /// </summary>
        internal static string StatisticPluginDescription {
            get {
                return ResourceManager.GetString("StatisticPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatisticPluginName {
            get {
                return ResourceManager.GetString("StatisticPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
