//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Plugin.FNA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Plugin.FNA.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthill.
        /// </summary>
        internal static string HovertextAnthillLine1 {
            get {
                return ResourceManager.GetString("HovertextAnthillLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony: {0}.
        /// </summary>
        internal static string HovertextAnthillLine2 {
            get {
                return ResourceManager.GetString("HovertextAnthillLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string HovertextAntLine1 {
            get {
                return ResourceManager.GetString("HovertextAntLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy: {0}.
        /// </summary>
        internal static string HovertextAntLine2 {
            get {
                return ResourceManager.GetString("HovertextAntLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        internal static string HovertextBugLine1 {
            get {
                return ResourceManager.GetString("HovertextBugLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy: {0}.
        /// </summary>
        internal static string HovertextBugLine2 {
            get {
                return ResourceManager.GetString("HovertextBugLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string HovertextFruitLine1 {
            get {
                return ResourceManager.GetString("HovertextFruitLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food: {0}.
        /// </summary>
        internal static string HovertextFruitLine2 {
            get {
                return ResourceManager.GetString("HovertextFruitLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar.
        /// </summary>
        internal static string HovertextSugarLine1 {
            get {
                return ResourceManager.GetString("HovertextSugarLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food: {0}.
        /// </summary>
        internal static string HovertextSugarLine2 {
            get {
                return ResourceManager.GetString("HovertextSugarLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beaten.
        /// </summary>
        internal static string InfoboxColumnBeatenAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnBeatenAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ants.
        /// </summary>
        internal static string InfoboxColumnBeatenAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnBeatenAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collected.
        /// </summary>
        internal static string InfoboxColumnCollectedFood1 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string InfoboxColumnCollectedFood2 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFood2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collected.
        /// </summary>
        internal static string InfoboxColumnCollectedFruits1 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFruits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit.
        /// </summary>
        internal static string InfoboxColumnCollectedFruits2 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFruits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InfoboxColumnColony1 {
            get {
                return ResourceManager.GetString("InfoboxColumnColony1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colony name.
        /// </summary>
        internal static string InfoboxColumnColony2 {
            get {
                return ResourceManager.GetString("InfoboxColumnColony2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eaten.
        /// </summary>
        internal static string InfoboxColumnEatenAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnEatenAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ants.
        /// </summary>
        internal static string InfoboxColumnEatenAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnEatenAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to killed.
        /// </summary>
        internal static string InfoboxColumnKilledAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ants.
        /// </summary>
        internal static string InfoboxColumnKilledAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to killed.
        /// </summary>
        internal static string InfoboxColumnKilledBugs1 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledBugs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs.
        /// </summary>
        internal static string InfoboxColumnKilledBugs2 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledBugs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InfoboxColumnPoints1 {
            get {
                return ResourceManager.GetString("InfoboxColumnPoints1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string InfoboxColumnPoints2 {
            get {
                return ResourceManager.GetString("InfoboxColumnPoints2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starved.
        /// </summary>
        internal static string InfoboxColumnStarvedAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnStarvedAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ants.
        /// </summary>
        internal static string InfoboxColumnStarvedAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnStarvedAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the simulation in 3D.
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D-Visualization.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
    }
}
