//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Gui.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fps.
        /// </summary>
        internal static string MainFramesPerSecond {
            get {
                return ResourceManager.GetString("MainFramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help available..
        /// </summary>
        internal static string MainMessageBoxNoHelpMessage {
            get {
                return ResourceManager.GetString("MainMessageBoxNoHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainMessageBoxNoHelpTitle {
            get {
                return ResourceManager.GetString("MainMessageBoxNoHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Mode selected.
        /// </summary>
        internal static string MainNoModeSelected {
            get {
                return ResourceManager.GetString("MainNoModeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string MainSpeedMaximal {
            get {
                return ResourceManager.GetString("MainSpeedMaximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0 fps.
        /// </summary>
        internal static string MainStateFramesPerSecond {
            get {
                return ResourceManager.GetString("MainStateFramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready.
        /// </summary>
        internal static string MainStateNotReady {
            get {
                return ResourceManager.GetString("MainStateNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string MainStatePaused {
            get {
                return ResourceManager.GetString("MainStatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MainStateReady {
            get {
                return ResourceManager.GetString("MainStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string MainStateRoundIndicator {
            get {
                return ResourceManager.GetString("MainStateRoundIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulating.
        /// </summary>
        internal static string MainStateRunning {
            get {
                return ResourceManager.GetString("MainStateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\\english\\Help.chm.
        /// </summary>
        internal static string MainTutorialPath {
            get {
                return ResourceManager.GetString("MainTutorialPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.antme.net/en.
        /// </summary>
        internal static string MainWebsiteLink {
            get {
                return ResourceManager.GetString("MainWebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /english/Welcome.htm.
        /// </summary>
        internal static string MainWelcomePagePath {
            get {
                return ResourceManager.GetString("MainWelcomePagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.antme.net/Application/StartPage?culture=en.
        /// </summary>
        internal static string MainWelcomePageUrl {
            get {
                return ResourceManager.GetString("MainWelcomePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.antme.net/en.
        /// </summary>
        internal static string MainWikiLink {
            get {
                return ResourceManager.GetString("MainWikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the plugin is empty..
        /// </summary>
        internal static string PluginItemConstructorPluginHasNoName {
            get {
                return ResourceManager.GetString("PluginItemConstructorPluginHasNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin was passed to the contructor..
        /// </summary>
        internal static string PluginItemConstructorPluginIsNull {
            get {
                return ResourceManager.GetString("PluginItemConstructorPluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin is not in the list of loaded plugins..
        /// </summary>
        internal static string PluginManagerActivateConsumerNotInList {
            get {
                return ResourceManager.GetString("PluginManagerActivateConsumerNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin is not in the list of loaded plugins..
        /// </summary>
        internal static string PluginManagerActivateProducerNotInList {
            get {
                return ResourceManager.GetString("PluginManagerActivateProducerNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were problems loading plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerConsumerPluginCommonProblems {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginCommonProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two different versions are available for plugin {0} ({1}). The one with the higher version number will be loaded..
        /// </summary>
        internal static string PluginManagerConsumerPluginNewerVersion {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A higher version of plugin {0} ({1}) is already loaded..
        /// </summary>
        internal static string PluginManagerConsumerPluginNewerVersionLoaded {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginNewerVersionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for plugin {0} ({1}) could not be loaded..
        /// </summary>
        internal static string PluginManagerConsumerPluginSettingsLoadFailed {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginSettingsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when saving settings of plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerConsumerPluginSettingsSaveFailed {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginSettingsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured in Plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerConsumerVisibilitySetFailed {
            get {
                return ResourceManager.GetString("PluginManagerConsumerVisibilitySetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin is not in the list of currently loaded plugins..
        /// </summary>
        internal static string PluginManagerDeactivateConsumerNotInList {
            get {
                return ResourceManager.GetString("PluginManagerDeactivateConsumerNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value has to be greater than 0..
        /// </summary>
        internal static string PluginManagerFrameRateTooLow {
            get {
                return ResourceManager.GetString("PluginManagerFrameRateTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerLoopConsumer1Failed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumer1Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerLoopConsumer2Failed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumer2Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerLoopConsumer3Failed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumer3Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems occured when refreshing the display in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerLoopConsumerUIFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumerUIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerLoopInterruptFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopInterruptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerLoopProducerFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopProducerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems occured when refreshing the display in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerLoopProducerUIFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopProducerUIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin could not be loaded. Missing references of plugin {0}..
        /// </summary>
        internal static string PluginManagerMissingReferences {
            get {
                return ResourceManager.GetString("PluginManagerMissingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were problems loading plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerProducerPluginCommonProblems {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginCommonProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two versions of plugin {0} ({1}) were found. The one with the higher version number will be loaded..
        /// </summary>
        internal static string PluginManagerProducerPluginNewerVersion {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A higher version of plugin {0} ({1}) has already been loaded..
        /// </summary>
        internal static string PluginManagerProducerPluginNewerVersionLoaded {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginNewerVersionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings of plugin {0} ({1}) could not be loaded..
        /// </summary>
        internal static string PluginManagerProducerPluginSettingsLoadFailed {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginSettingsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems occurred when attempting to save the settings of plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerProducerPluginSettingsSaveFailed {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginSettingsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem in plugin {0} ({1})..
        /// </summary>
        internal static string PluginManagerProducerVisibilitySetFailed {
            get {
                return ResourceManager.GetString("PluginManagerProducerVisibilitySetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration could not be loaded. This is likely due to an old version..
        /// </summary>
        internal static string PluginManagerSettingsLoadFailed {
            get {
                return ResourceManager.GetString("PluginManagerSettingsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are problems to reach the AntMe! Update Service. Please check your internet connection.
        /// </summary>
        internal static string UpdateErrorMessage {
            get {
                return ResourceManager.GetString("UpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a newer Version of AntMe! available. Do you want to download it?.
        /// </summary>
        internal static string UpdateNewerMessage {
            get {
                return ResourceManager.GetString("UpdateNewerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the newest Version of AntMe!.
        /// </summary>
        internal static string UpdateNewestMessage {
            get {
                return ResourceManager.GetString("UpdateNewestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string UpdateNoConnection {
            get {
                return ResourceManager.GetString("UpdateNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntMe! Update.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to Login again.
        /// </summary>
        internal static string UpdateTokenInvalid {
            get {
                return ResourceManager.GetString("UpdateTokenInvalid", resourceCulture);
            }
        }
    }
}
