//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string SettingsDefaultName {
            get {
                return ResourceManager.GetString("SettingsDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to cheat with a fake Framework assembly..
        /// </summary>
        internal static string SimulationCoreAnalysisCheatWithFxFake {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisCheatWithFxFake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External reference:.
        /// </summary>
        internal static string SimulationCoreAnalysisForeignRefInfotext {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisForeignRefInfotext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ant was likely created with a newer version of AntMe!..
        /// </summary>
        internal static string SimulationCoreAnalysisNewerVersion {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain a class with this name..
        /// </summary>
        internal static string SimulationCoreAnalysisNoClassFound {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisNoClassFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ant class that was found ({0}) is not decorated with a PlayerAttribute..
        /// </summary>
        internal static string SimulationCoreAnalysisNoPlayerAttribute {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisNoPlayerAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ants of version 1.1 or lower are not supported in this version anymore..
        /// </summary>
        internal static string SimulationCoreAnalysisNotSupportedAntVersion {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisNotSupportedAntVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to load an earlier ant simulation core (version: {0}) failed..
        /// </summary>
        internal static string SimulationCoreAnalysisOldAssemblyLoadFailed {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisOldAssemblyLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ant class {0} containas more than one PlayerAttribute..
        /// </summary>
        internal static string SimulationCoreAnalysisTooManyPlayerAttributes {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisTooManyPlayerAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external reference &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string SimulationCoreAnalysisUnknownReferenceLoadFailed {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisUnknownReferenceLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ant could not be assigned a version. {0}.
        /// </summary>
        internal static string SimulationCoreAnalysisUnknownVersion {
            get {
                return ResourceManager.GetString("SimulationCoreAnalysisUnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attack-modificator of caste {0} of ant {1} is invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleAttackFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleAttackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The energy-modificator of caste {0} of ant {1} is invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleEnergyFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleEnergyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load-modificator of caste {0} of ant {1} is invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleLoadFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caste-attribute of ant {0} does not contain a name..
        /// </summary>
        internal static string SimulationCoreCasteRuleNoName {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reach-modificator of caste {0} of ant {1} is invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleRangeFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rotationspeed-modificator of caste {0} of ant {1}is invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleRotationSpeedFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleRotationSpeedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The speed-modificator of caste {0} of ant {1} is invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleSpeedFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleSpeedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of modificators of caste {0} of player {1} are invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleSumFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleSumFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The viewrange-modificator of caste {0} of ant {1} is invalid..
        /// </summary>
        internal static string SimulationCoreCasteRuleViewRangeFailed {
            get {
                return ResourceManager.GetString("SimulationCoreCasteRuleViewRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired caste for the new ant &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string SimulationCoreChooseWrongCaste {
            get {
                return ResourceManager.GetString("SimulationCoreChooseWrongCaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loop count cannot be greater than {0}..
        /// </summary>
        internal static string SimulationCoreConfigurationLoopCountTooBig {
            get {
                return ResourceManager.GetString("SimulationCoreConfigurationLoopCountTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum loop count is 1..
        /// </summary>
        internal static string SimulationCoreConfigurationLoopCountTooSmall {
            get {
                return ResourceManager.GetString("SimulationCoreConfigurationLoopCountTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout value for a loop cannot be less than 1..
        /// </summary>
        internal static string SimulationCoreConfigurationLoopTimeoutTooSmall {
            get {
                return ResourceManager.GetString("SimulationCoreConfigurationLoopTimeoutTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one team must be selected for the simulation..
        /// </summary>
        internal static string SimulationCoreConfigurationNoTeams {
            get {
                return ResourceManager.GetString("SimulationCoreConfigurationNoTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The round count must not exceed {0}..
        /// </summary>
        internal static string SimulationCoreConfigurationRoundCountTooBig {
            get {
                return ResourceManager.GetString("SimulationCoreConfigurationRoundCountTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum round count is 1..
        /// </summary>
        internal static string SimulationCoreConfigurationRoundCountTooSmall {
            get {
                return ResourceManager.GetString("SimulationCoreConfigurationRoundCountTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout value for a round cannot be less than 1..
        /// </summary>
        internal static string SimulationCoreConfigurationRoundTimeoutTooSmall {
            get {
                return ResourceManager.GetString("SimulationCoreConfigurationRoundTimeoutTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter configuration must not be null..
        /// </summary>
        internal static string SimulationCoreFactoryConfigIsNull {
            get {
                return ResourceManager.GetString("SimulationCoreFactoryConfigIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment has not yet been initialized..
        /// </summary>
        internal static string SimulationCoreHostEnvironmentNotInit {
            get {
                return ResourceManager.GetString("SimulationCoreHostEnvironmentNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout for a round has been exceeded..
        /// </summary>
        internal static string SimulationCoreHostRoundTimeout {
            get {
                return ResourceManager.GetString("SimulationCoreHostRoundTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration may only contain PlayerInfoFileName or PlayerInfoFileDump..
        /// </summary>
        internal static string SimulationCoreHostWrongPlayerInfo {
            get {
                return ResourceManager.GetString("SimulationCoreHostWrongPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to create marker with size smaller than 0.
        /// </summary>
        internal static string SimulationCoreNegativeMarkerSize {
            get {
                return ResourceManager.GetString("SimulationCoreNegativeMarkerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the player attribute of class {0} does not contain a name..
        /// </summary>
        internal static string SimulationCorePlayerRuleNoName {
            get {
                return ResourceManager.GetString("SimulationCorePlayerRuleNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The simulation has already been unloaded..
        /// </summary>
        internal static string SimulationCoreProxyUnloaded {
            get {
                return ResourceManager.GetString("SimulationCoreProxyUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration may only contain PlayerInfoFileName or PlayerInfoFileDump..
        /// </summary>
        internal static string SimulationCoreProxyWrongPlayerInfo {
            get {
                return ResourceManager.GetString("SimulationCoreProxyWrongPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no rights to grand database-access to various colonies..
        /// </summary>
        internal static string SimulationCoreRightsConflictDb {
            get {
                return ResourceManager.GetString("SimulationCoreRightsConflictDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no rights to grand file-access to various colonies..
        /// </summary>
        internal static string SimulationCoreRightsConflictIo {
            get {
                return ResourceManager.GetString("SimulationCoreRightsConflictIo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no rights to grand network-access to various colonies..
        /// </summary>
        internal static string SimulationCoreRightsConflictNet {
            get {
                return ResourceManager.GetString("SimulationCoreRightsConflictNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no rights to grand userinterface-access to various colonies..
        /// </summary>
        internal static string SimulationCoreRightsConflictUi {
            get {
                return ResourceManager.GetString("SimulationCoreRightsConflictUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of the caste column is too large..
        /// </summary>
        internal static string SimulationCoreSettingsCasteColumnToBig {
            get {
                return ResourceManager.GetString("SimulationCoreSettingsCasteColumnToBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of the caste column is too small..
        /// </summary>
        internal static string SimulationCoreSettingsCasteColumnToSmall {
            get {
                return ResourceManager.GetString("SimulationCoreSettingsCasteColumnToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call Step() on a simulation that has already completed..
        /// </summary>
        internal static string SimulationCoreSimulatorRestartFailed {
            get {
                return ResourceManager.GetString("SimulationCoreSimulatorRestartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of players of a team may not be empty..
        /// </summary>
        internal static string SimulationCoreTeamInfoNoName {
            get {
                return ResourceManager.GetString("SimulationCoreTeamInfoNoName", resourceCulture);
            }
        }
    }
}
